spring:
  application:
    name: transaction-service
  datasource:
    url: jdbc:h2:mem:transactiondb
    driverClassName: org.h2.Driver
    password: password
    username: admin
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  sql:
    init:
      platform: h2
      mode: always
  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 8083
  servlet:
    context-path: /transaction-service

client:
  auth:
    properties:
      "[customer-service]": "V0ppUFVsT3FGUjRQWHZhTWYxWmlVRnhhSGNHNVNvVWM="
      "[query-service]": "NVlWa1lJVHhTM2E4RjNpOTBYSkJPSzZMVzdMU1gzZWM="
