spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:h2:mem:customerdb
    driverClassName: org.h2.Driver
    password: password
    username: admin
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  sql:
    init:
      platform: h2
      mode: always

server:
  port: 8080
  servlet:
    context-path: /customer-service

client:
  auth:
    properties:
      "[api-gateway]": "SzIwdzl0VHpsVFhuc2hZTmx2R2M5MzYyMDgwVHNzbWk="
