spring:
  application:
    name: query-service

server:
  port: 8084
  servlet:
    context-path: /query-service


customer:
  service:
    url: http://customer-service:8085/customer-service/

account:
  service:
    url: http://account-service:8082/account-service/

transaction:
  service:
    url: http://transaction-service:8083/transaction-service/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

client:
  auth:
    properties:
      "[api-gateway]": "SzIwdzl0VHpsVFhuc2hZTmx2R2M5MzYyMDgwVHNzbWk="
      "[query-service]": "N2RGclZRR0psTERLcE9SVGhEaGYyd3cwNjhTUlh0RVI="
