pipeline {
    agent any
    environment {
        SERVICE_NAME = 'query-service'
        DOCKER_REGISTRY = 'your-docker-registry'
        DOCKER_IMAGE = "${DOCKER_REGISTRY}/${SERVICE_NAME}"
    }
    stages {
        stage('Checkout') {
            steps {
                git branch: 'master', url: 'https://github.com/macibadem/deposit.git'
            }
        }
        stage('Build') {
            steps {
                dir('query-service') {
                    sh './mvnw clean package -DskipTests'
                }
            }
        }
        stage('Docker Build & Push') {
            steps {
                dir('query-service') {
                    sh "docker build -t ${DOCKER_IMAGE}:${env.BUILD_NUMBER} ."
                    sh "docker push ${DOCKER_IMAGE}:${env.BUILD_NUMBER}"
                }
            }
        }
        stage('Deploy') {
            steps {
                sh """
                kubectl set image deployment/${SERVICE_NAME} ${SERVICE_NAME}=${DOCKER_IMAGE}:${env.BUILD_NUMBER}
                """
            }
        }
    }
}
