spring:
  application:
    name: account-service
  datasource:
    url: jdbc:h2:mem:accountdb
    driverClassName: org.h2.Driver
    password: password
    username: admin
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  sql:
    init:
      platform: h2
      mode: always
  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 8082
  servlet:
    context-path: /account-service

client:
  auth:
    properties:
      "[api-gateway]": "SzIwdzl0VHpsVFhuc2hZTmx2R2M5MzYyMDgwVHNzbWk="
      "[query-service]": "N2RGclZRR0psTERLcE9SVGhEaGYyd3cwNjhTUlh0RVI="
